def format_for_whatsapp(notes):
    """
    Converts Gemini's structured MeetingNotes object
    into a clean WhatsApp-friendly message.
    """

    # Pydantic model -> normal dictionary
    if hasattr(notes, "model_dump"):
        data = notes.model_dump()
    else:
        data = notes


    def bullet_list(items):

        if not items:
            return "_None_"

        return "\n".join(
            f"• {item}"
            for item in items
        )


    def action_items(items):

        if not items:
            return "_None_"

        lines = []

        for item in items:

            task = item.get(
                "task",
                ""
            )

            deadline = item.get(
                "deadline"
            )

            if deadline:

                lines.append(
                    f"• {task}\n"
                    f"  _Deadline: {deadline}_"
                )

            else:

                lines.append(
                    f"• {task}"
                )

        return "\n".join(lines)


    decisions = [
        item["decision"]
        for item in data.get(
            "decisions",
            []
        )
    ]


    text = f"""*MEETING NOTES*

*{data.get("title", "Meeting")}*

*SUMMARY*
{data.get("summary", "")}


*KEY POINTS*
{bullet_list(data.get("key_points", []))}


*DECISIONS*
{bullet_list(decisions)}


*MY ACTION ITEMS*
{action_items(data.get("my_action_items", []))}


*CLIENT ACTION ITEMS*
{action_items(data.get("client_action_items", []))}


*DEADLINES*
{bullet_list(data.get("deadlines", []))}


*FOLLOW-UP*
{data.get("follow_up") or "_None_"}

_Generated by WhatsApp Meeting Assistant_
"""

    return text.strip()